# Numpy Crash Course

In [53]:
import numpy as np

In [54]:
np.__version__

'2.4.6'

In [55]:
import sys
sys.version

'3.14.6 | packaged by Anaconda, Inc. | (main, Jul  9 2026, 14:29:05) [MSC v.1942 64 bit (AMD64)]'

In [56]:
#Create a List
my_list = [2,3,4,5,6,7]
my_list

[2, 3, 4, 5, 6, 7]

In [57]:
type(my_list)

list

In [58]:
arr = np.array(my_list)
arr

array([2, 3, 4, 5, 6, 7])

In [59]:
type(arr)

numpy.ndarray

In [60]:
print(type(my_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [61]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [62]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [63]:
np.arange(5,100,10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [64]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [65]:
np.arange(20,10)  # first argument must be small one

array([], dtype=int64)

In [66]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [67]:
np.zeros(5) # Parameter Tunning

array([0., 0., 0., 0., 0.])

In [68]:
np.zeros(5, dtype=int) # One Dimension Array --HyperPerameter

array([0, 0, 0, 0, 0])

In [69]:
np.zeros((2,2)) # Two dimentional Array

array([[0., 0.],
       [0., 0.]])

In [70]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [71]:
np.zeros((10,10), dtype=int) # End Dimentional Array

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [72]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [73]:
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [74]:
np.random.rand(3)

array([0.4832446 , 0.26685227, 0.43423406])

In [75]:
np.random.rand(3)

array([0.31126252, 0.96704054, 0.14605741])

In [76]:
np.random.rand(23)

array([0.46968396, 0.19959814, 0.42092009, 0.2680572 , 0.34174243,
       0.7454019 , 0.00578387, 0.14012552, 0.93011109, 0.44781978,
       0.5691235 , 0.58668472, 0.85395642, 0.9083576 , 0.67439884,
       0.57913342, 0.7604491 , 0.80179662, 0.96707334, 0.71751065,
       0.57670688, 0.30881051, 0.02081933])

In [77]:
np.random.randint(2)

1

In [78]:
np.random.randint(11,15)

12

In [79]:
np.random.randint(11,21,7) #generate random number between 11 to 21 and exclude 21

array([16, 13, 14, 16, 13, 14, 13], dtype=int32)

In [80]:
import random

otp = random.randint(100000, 999999)

print("Your OTP is:", otp)

Your OTP is: 607774


In [81]:
np.random.randint(10,40,(10,10)) #without variable it display dtype=int32

array([[28, 32, 27, 10, 32, 17, 14, 35, 22, 39],
       [31, 33, 34, 32, 25, 35, 27, 17, 36, 10],
       [32, 14, 22, 19, 11, 20, 21, 34, 14, 13],
       [39, 18, 19, 14, 10, 32, 35, 33, 30, 25],
       [11, 22, 27, 19, 18, 24, 15, 16, 17, 26],
       [16, 13, 16, 25, 34, 34, 32, 33, 15, 29],
       [26, 37, 39, 18, 10, 13, 32, 36, 29, 21],
       [14, 14, 12, 29, 11, 33, 28, 22, 14, 25],
       [32, 11, 26, 17, 23, 17, 29, 39, 27, 13],
       [25, 37, 10, 32, 30, 35, 23, 29, 24, 15]], dtype=int32)

In [82]:
arr1 = np.random.randint(10,40,(10,10))
print(arr1)

[[13 28 37 33 37 20 22 35 32 37]
 [16 18 24 27 16 20 31 18 37 16]
 [17 11 14 20 39 29 33 24 20 22]
 [18 36 24 20 30 25 19 13 33 35]
 [14 28 28 10 20 38 16 39 10 22]
 [10 29 35 37 27 28 35 31 19 12]
 [30 21 32 11 37 28 15 19 11 15]
 [36 31 18 12 36 39 23 18 32 31]
 [24 22 35 20 38 38 26 27 23 10]
 [14 15 34 26 19 22 16 15 29 32]]


In [83]:
arr1[3]

array([18, 36, 24, 20, 30, 25, 19, 13, 33, 35], dtype=int32)

In [84]:
arr1[-3]

array([36, 31, 18, 12, 36, 39, 23, 18, 32, 31], dtype=int32)

In [85]:
arr1[0]

array([13, 28, 37, 33, 37, 20, 22, 35, 32, 37], dtype=int32)

In [86]:
arr2 = np.random.randint(1,9,(5,7))
print(arr2)

[[2 1 2 1 4 3 4]
 [7 2 6 3 1 4 5]
 [4 5 2 4 4 6 1]
 [2 6 3 5 1 6 1]
 [6 4 6 6 1 5 2]]


In [87]:
arr2[2:10]

array([[4, 5, 2, 4, 4, 6, 1],
       [2, 6, 3, 5, 1, 6, 1],
       [6, 4, 6, 6, 1, 5, 2]], dtype=int32)

In [88]:
arr2[:]

array([[2, 1, 2, 1, 4, 3, 4],
       [7, 2, 6, 3, 1, 4, 5],
       [4, 5, 2, 4, 4, 6, 1],
       [2, 6, 3, 5, 1, 6, 1],
       [6, 4, 6, 6, 1, 5, 2]], dtype=int32)

In [89]:
arr1[2:5,2:5]

array([[14, 20, 39],
       [24, 20, 30],
       [28, 10, 20]], dtype=int32)

In [90]:
arr1[arr1>5] #filter inArray

array([13, 28, 37, 33, 37, 20, 22, 35, 32, 37, 16, 18, 24, 27, 16, 20, 31,
       18, 37, 16, 17, 11, 14, 20, 39, 29, 33, 24, 20, 22, 18, 36, 24, 20,
       30, 25, 19, 13, 33, 35, 14, 28, 28, 10, 20, 38, 16, 39, 10, 22, 10,
       29, 35, 37, 27, 28, 35, 31, 19, 12, 30, 21, 32, 11, 37, 28, 15, 19,
       11, 15, 36, 31, 18, 12, 36, 39, 23, 18, 32, 31, 24, 22, 35, 20, 38,
       38, 26, 27, 23, 10, 14, 15, 34, 26, 19, 22, 16, 15, 29, 32],
      dtype=int32)

In [91]:
arr1[arr1 == 5]

array([], dtype=int32)

In [92]:
arr1[arr1 != 5]

array([13, 28, 37, 33, 37, 20, 22, 35, 32, 37, 16, 18, 24, 27, 16, 20, 31,
       18, 37, 16, 17, 11, 14, 20, 39, 29, 33, 24, 20, 22, 18, 36, 24, 20,
       30, 25, 19, 13, 33, 35, 14, 28, 28, 10, 20, 38, 16, 39, 10, 22, 10,
       29, 35, 37, 27, 28, 35, 31, 19, 12, 30, 21, 32, 11, 37, 28, 15, 19,
       11, 15, 36, 31, 18, 12, 36, 39, 23, 18, 32, 31, 24, 22, 35, 20, 38,
       38, 26, 27, 23, 10, 14, 15, 34, 26, 19, 22, 16, 15, 29, 32],
      dtype=int32)

In [93]:
arr2

array([[2, 1, 2, 1, 4, 3, 4],
       [7, 2, 6, 3, 1, 4, 5],
       [4, 5, 2, 4, 4, 6, 1],
       [2, 6, 3, 5, 1, 6, 1],
       [6, 4, 6, 6, 1, 5, 2]], dtype=int32)

In [94]:
arr

array([2, 3, 4, 5, 6, 7])

In [95]:
arr2

array([[2, 1, 2, 1, 4, 3, 4],
       [7, 2, 6, 3, 1, 4, 5],
       [4, 5, 2, 4, 4, 6, 1],
       [2, 6, 3, 5, 1, 6, 1],
       [6, 4, 6, 6, 1, 5, 2]], dtype=int32)

In [97]:
arr.reshape(2,3)

array([[2, 3, 4],
       [5, 6, 7]])

In [98]:
arr.reshape(1,6)

array([[2, 3, 4, 5, 6, 7]])

In [99]:
arr.reshape(6,1)

array([[2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [101]:
arr.max()

np.int64(7)

In [102]:
arr.min()

np.int64(2)