# Array Creation Function

In [6]:
import numpy as np

In [7]:
# Create an array from a list
a = np.array([1,2,3])
print("Array a:" ,a)

Array a: [1 2 3]


In [8]:
b = np.arange(0,10,3)
print("Array b: " , b)

Array b:  [0 3 6 9]


In [9]:
d = np.zeros((2,3), dtype=int)
print("Array d:\n",d)

Array d:
 [[0 0 0]
 [0 0 0]]


In [10]:
e = np.ones((3,2), dtype=int)
print("Array e:\n",e)

Array e:
 [[1 1]
 [1 1]
 [1 1]]


In [11]:
f = np.eye(4,dtype=int)
print("Identity Matrix f:\n" ,f)

Identity Matrix f:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


# Array Manipulation

In [12]:
a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(1,3))  # Reshape to 1*3
print("Reshaped Array:",reshaped)

Reshaped Array: [[1 2 3]]


In [13]:
a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(3,1))  # Reshape to 1*3
print("Reshaped Array:",reshaped)

Reshaped Array: [[1]
 [2]
 [3]]


In [14]:
f1 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
flattened = np.ravel(f1) # Flatten to 10 array
print("Flattenned Array: " ,flattened)

Flattenned Array:  [ 1  2  3  4  5  6  7  8  9 10]


In [15]:
e1 = np.array([[1,2],[3,4]])
transposed = np.transpose(e1) # Flatten to 10 array
print("Transposed Array:\n " ,transposed)

Transposed Array:
  [[1 3]
 [2 4]]


In [16]:
# Stack Array Vertical
a2  = np.array([1,2])
b2  = np.array([3,4])
stacked = np.vstack([a2,b2]) # Stack a and b vertically
print("Stacked Array: \n",stacked)

Stacked Array: 
 [[1 2]
 [3 4]]


In [17]:
# Stack Array Horizontal
a2  = np.array([1,2])
b2  = np.array([3,4])
stacked = np.hstack([a2,b2])  # Stack a and b horizontally
print("Stacked Array: \n",stacked)

Stacked Array: 
 [1 2 3 4]


# Mathematical Functions

In [18]:
g = np.array([1,2,3,4])
added = np.add(g, 2) # Add 2 to each element
print("Added 2 to g:",added)

Added 2 to g: [3 4 5 6]


In [19]:
squared = np.power(g, 2) #Square each element
print("Square g:",squared)

Square g: [ 1  4  9 16]


In [20]:
sqrt_val = np.sqrt(g) #Square each element
print("Square root of g: \n",sqrt_val)

Square root of g: 
 [1.         1.41421356 1.73205081 2.        ]


In [21]:
print(a)
print(g)

[1 2 3]
[1 2 3 4]


In [22]:
a3 = np.array([1,2,3])
dot_product = np.dot(a,g) # Dot Rroduct of a and b
print("Dot Product of a and g:" ,dot_product)
# got an error dimention not match

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [ ]:
print(a)
print(a1)

In [23]:
a3 = np.array([1,2,3])
dot_product = np.dot(a1,a) # Dot Rroduct of a and b
print("Dot Product of a and g:" ,dot_product)

Dot Product of a and g: 14


# Statistical Numpy

In [24]:
s = np.array([1,2,3,4])
mean = np.mean(s)
print("Mean of s: ", mean)

Mean of s:  2.5


In [25]:
var  = np.var(s)
print("Variable of s:" ,var)

Variable of s: 1.25


In [26]:
# Standard deviation of an array
std_dev = np.std(s)
print("Standard deviation of s:" ,std_dev)

Standard deviation of s: 1.118033988749895


In [27]:
minimum = np.min(s)
print("Min of s:" ,minimum)

Min of s: 1


In [28]:
maximum = np.max(s)
print("Maximum of s:" ,maximum)

Maximum of s: 4


# Random Sampling Function

In [29]:
#Genarate Random Values
random_vals = np.random.rand(3)
print("Randon values:" ,random_vals)

Randon values: [0.91153771 0.94623773 0.28195112]


In [30]:
#Genarate Random Values
random_ints = np.random.randint(0,10, size=4) #Random Integer 0 t0 10
print("Randon values:" ,random_ints)

Randon values: [2 0 6 5]


In [31]:
np.random.seed(0)
random_ints = np.random.randint(0,10, size=6) # Constant Integer 0 t0 10
print("Randon values:" ,random_ints)

Randon values: [5 0 3 3 7 9]


In [32]:
np.random.seed(0)
random_ints = np.random.randint(0,10, size=6) # Constant Integer 0 t0 10
print("Randon values:" ,random_ints)

Randon values: [5 0 3 3 7 9]


# Boolean and Logical Functions

In [33]:
# Check if all elements are True 
logical_test = np.array([True, False, True]) 
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [34]:
# Check if all elements are True
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [35]:
# Check if all elements are True
logical_test = np.array([False, False, False])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False
